[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Monitor settings
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=3

; Library dependencies
lib_deps = 
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/RTClib@^2.1.3
    bblanchon/ArduinoJson@^7.0.4
    dfrobot/DFRobotDFPlayerMini@^1.0.6

; Upload settings (sesuaikan dengan port ESP32 anda)
; upload_port = /dev/cu.usbserial-0001
; upload_port = /dev/cu.wchusbserial22220
upload_port = /dev/cu.wchusbserial1410
upload_speed = 115200
upload_flags = 
    --before=default_reset
    --after=hard_reset

; Monitor port (auto-detect by default)
; monitor_port = /dev/cu.usbserial-0001
